import type { ProjectManifest } from "@threeforge/schemas";

export function generatePackageJson(options: {
  name: string;
  manifest: ProjectManifest;
}): Record<string, unknown> {
  const pkgName = slugify(options.name);
  return {
    name: pkgName,
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      dev: "vite",
      build: "tsc --noEmit && vite build",
      preview: "vite preview",
    },
    dependencies: {
      three: "^0.166.1",
      "@threeforge/engine": "file:./vendor/@threeforge/engine",
      "@threeforge/schemas": "file:./vendor/@threeforge/schemas",
    },
    devDependencies: {
      typescript: "^5.5.4",
      vite: "^5.4.0",
      "@types/three": "^0.166.0",
    },
  };
}

export function generateReadme(options: {
  name: string;
  defaultScene: string;
}): string {
  return `# ${options.name}

Exported Three.js game project generated by ThreeForge.

## Run

\`\`\`bash
npm install
npm run dev
\`\`\`

## Build

\`\`\`bash
npm run build
\`\`\`

## Notes

- Default scene: \`${options.defaultScene}\`
- Scripts use the public \`@threeforge/engine\` Behaviour API only.
- This package does **not** include the Tauri editor, MCP server, or AI tools.
`;
}

function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "threeforge-game"
  );
}
